import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.scss";
import Header from "./components/Header";

// Load the Montserrat font with specific subsets and weights
const inter = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Digital Booster",
  description: "Generated by create next app",
  openGraph: {
    title: "Digital Booster",
    description: "Generated by create next app",
    images: {
      url: "/logo.svg",
      width: 1920,
      height: 1080,
    },
    type: "website",
  },
  robots: {
    index: false,
    follow: false
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
